### ISSUE TITLE
Image Upload Refactor

### ISSUE THREAD

**Issue by JoeMics** [JoeMics/CollaborEats#95]
Currently our image upload is done using gridFS, and multer. 

To resolve:

- [ ] use 3rd party API for image storage

**Comment by tangivan** [comment]
Things done so far:
f253881411387afa5ac1aa11c9a6138ee190a120 For AWS S3 setup
0b760ad525c058bf3933a99949da9ebd987d6402 Api calls to use Image uploading all setup
47cb4698e3f90a2d936ada87e9648f113fc96351 Example code and testing page now live on production 

Need further discussion on redoing how image links are shown before full refactor and closing issue

**Comment by tangivan** [comment]
d54f9f47efd14de76e1bf8b63189cb6104235c68 AWS S3 setup fully integrated with production build
